---

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
      # General
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-yaml
          - id: detect-private-key
          - id: double-quote-string-fixer
          - id: end-of-file-fixer
          - id: mixed-line-ending # Replaces or checks mixed line ending.
          - id: trailing-whitespace

  # General

    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.2.0
      hooks:
          - id: detect-secrets
            args: [--baseline, .secrets.baseline]
            exclude: package.lock.json

    - repo: https://github.com/sirosen/texthooks
      rev: 0.3.1
      hooks:
          - id: fix-smartquotes
          - id: fix-ligatures

  # Git

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.17.0
      hooks:
          - id: gitlint

  # Markdown

    - repo: https://github.com/executablebooks/mdformat
      rev: 0.7.14
      hooks:
          - id: mdformat

  # YAML

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.26.3
      hooks:
          - id: yamllint
            args: [-c=.yamllint.yml]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.1
      hooks:
          - id: yamlfmt

  # Mixed

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 2.1.6
      hooks:
          - id: forbid-binary
          - id: git-check # Configure in .gitattributes

    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.13
      hooks:
          - id: remove-crlf
          - id: remove-tabs
            exclude: .git/COMMIT_EDITMSG

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.14.2
      hooks:
          - id: check-github-actions
          - id: check-github-workflows
          - id: check-readthedocs
