---

name: Pull Requests & Pushes

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:

  pre-commit:
    name: Run pre-commit actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: pre-commit
        uses: pre-commit/action@v2.0.2
